version: '3.9'

services:
  db:
    container_name: db
    image: postgres:latest
    environment: # Configuração do banco.
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql #Caminho dos arquivos bin no volume.
      - postgresql_data:/var/lib/postgresql/data #Caminho dos dados no volume.
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql # Cria tabelas e adiciona os dados do banco northwind.
      - ./files:/files
    ports:
      - 55432:5432
    networks:
      - nome-sua-rede

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: #Configurações de acesso pgadmin.
      PGADMIN_DEFAULT_EMAIL: seu-email@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
      - ./files:/files
    ports:
      - 5050:5050
    networks:
      - nome-sua-rede

  dbt:
    build: . # Cria o conteiner dbt a partir do projeto local.
    container_name: dbt
    volumes:
      - ./workflow:/app
      - ./workflow/profiles.yml:/root/.dbt/profiles.yml
    ports:
      - "8080:8080"
    networks:
      - nome-sua-rede
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: tail -f /dev/null # Mantem o conteiner com o dbt rodando.

volumes:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local

networks:
  nome-sua-rede:
    driver: bridge
